name: Publish VS Code Extension

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:
        inputs:
            version_increment:
                description: "Version increment type"
                required: true
                default: "patch"
                type: "choice"
                options:
                    - "none"
                    - "patch"
                    - "minor"
                    - "major"

jobs:
    package-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Upgrade npm
              run: |
                  npm --version
                  npm i -g npm@latest
                  npm --version

            - name: Install dependencies (root)
              run: npm install --no-audit --no-fund

            - name: Install workspace packages explicitly
              run: >-
                  npm install --no-audit --no-fund
                  -w packages/core
                  -w packages/vscode-extension

            - name: Increment version if requested
              if: github.event_name == 'workflow_dispatch' && github.event.inputs.version_increment != 'none'
              run: |
                  cd packages/vscode-extension
                  npm version ${{ github.event.inputs.version_increment }} --no-git-tag-version

                  # Extract version for later use
                  VERSION=$(node -p "require('./package.json').version")
                  echo "EXTENSION_VERSION=$VERSION" >> $GITHUB_ENV
                  cd ../..

            - name: Build extension
              run: npm run vsce:package

            - name: Verify .vsix exists
              run: |
                  if [ ! -f baseline-guardrails-vscode.vsix ]; then
                    echo "Error: VSIX package not found!"
                    exit 1
                  fi

                  echo "VSIX package successfully built!"

            - name: Publish to VS Code Marketplace
              if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.version_increment != 'none')
              run: |
                  cd packages/vscode-extension
                  npx @vscode/vsce publish --packagePath ../../baseline-guardrails-vscode.vsix -p ${{ secrets.VSCE_PAT }}
                  cd ../..

            - name: Upload VSIX artifact
              uses: actions/upload-artifact@v4
              with:
                  name: baseline-guardrails-vscode
                  path: baseline-guardrails-vscode.vsix

            - name: Create GitHub Release
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v1
              with:
                  files: baseline-guardrails-vscode.vsix
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
