name: Release CLI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      create_pr:
        description: "Create a release PR (true) or publish directly (false)"
        required: false
        default: "true"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - name: Upgrade npm
        run: |
          npm --version
          npm i -g npm@latest
          npm --version
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Build
        run: npm run build
      # Auth sanity check (lightweight)
      - name: NPM auth check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Registry: $(npm config get registry)"
          npm whoami
      - name: Version / Publish (PR or direct)
        uses: changesets/action@v1
        with:
          publish: npm run release:publish
          version: npm run release:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Direct version/publish path removed (simplified to single changesets step)

      - name: Upload npm debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs
