name: Release Packages

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Upgrade npm
        run: |
          npm --version
          npm i -g npm@latest
          npm --version
      - name: Ensure workspaces enabled
        run: |
          npm config set workspaces true
          npm config get workspaces
      - name: Install deps (root)
        run: npm install --no-audit --no-fund

      - name: Install workspace packages explicitly
        run: >-
          npm install --no-audit --no-fund
          -w packages/core
          -w packages/helpers
          -w packages/cli
          -w packages/action
          -w packages/eslint-plugin-baseline
          -w packages/lsp-server
          -w packages/vscode-extension
      - name: Build
        run: npm run build
      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          publish: npm run release:publish
          version: npm run release:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
