name: Package VS Code Extension

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci || npm i
      - name: Build
        run: npm run build
      - name: Install VSCE
        run: npm i -g @vscode/vsce
      - name: Package extension (staged)
        run: |
          node packages/vscode-extension/scripts/bundle-core.cjs
          node packages/vscode-extension/scripts/pack.cjs
      - name: Upload vsix artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-guardrails-vscode
          path: baseline-guardrails-vscode.vsix
